[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "NoCompanyPenalties"
description = "Disable dying penalties on Company moons."
websiteUrl = "https://github.com/AndreyMrovol/NoCompanyPenalties"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-MrovLib = "0.2.22"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../NoCompanyPenalties/dist"

[[build.copy]]
source = "../NoCompanyPenalties/bin/Release/netstandard2.1/NoCompanyPenalties.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]